#!/usr/bin/env bash

ip="139.144.35.21";
if [[ ! -z $IP ]]; then
    ip=$IP
fi

file=$1
if [[ ! -z $FILE ]]; then
    file=$FILE
fi

depth=$2
if [[ ! -z $DEPTH ]]; then
    depth=$DEPTH
fi

count=$3
if [[ ! -z $COUNT ]]; then
    count=$COUNT
fi

echo "Using $ip $file $depth $count"
ulimit -n 10000
# max_conn=("20" "50" "100" "200" "500" "1000")
max_conn=("50" "100" "200" "500")
for conn in ${max_conn[@]}; do
    echo "running $conn"
    ./testies --address $ip --depth $depth --girth 1000 --count $count -m $conn > $file.$depth.$count.$conn
done
scp root@$ip:/root/mem.out $file.$depth.$count.mem


