#!/usr/bin/env zsh

ip="139.144.35.21";
if [[ ! -z $IP ]]; then
    ip=$IP
fi
echo "Using $ip"
ulimit -n 10000
# max_conn=("20" "50" "100" "200" "500" "1000")
max_conn=("16" "50" "100")
for conn in $max_conn; do
    echo "running $conn"
    cargo run --release --bin testies -- --address $ip --depth $2 --girth 1000 --count $3 -t 16 -m $conn > $1.$2.$3.$conn$4
done
# scp root@$ip:/root/mem.out $1.$2.$3$4.mem

